title: 김시안의 기술블로그
description: 김시안의 기술블로그 입니다.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://chlosesian.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: '시안'
  last_name: '김'
  cv: '//kaptn.ru'
  github_username:  chloesian  
  email: vika@kaptn.ru
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


